[package]
name = "grevm"
version = "0.1.0"
edition = "2024"
description = "Create Parallel EVM"
build = "build.rs"

[dependencies]
revm = { package = "revm", git = "https://github.com/Galxe/revm", rev = "719cd933", default-features = false }
revm-database = { package = "revm-database", git = "https://github.com/Galxe/revm", rev = "719cd933", default-features = false }
revm-state = { package = "revm-state", git = "https://github.com/Galxe/revm", rev = "719cd933", default-features = false }
revm-primitives = { package = "revm-primitives", git = "https://github.com/Galxe/revm", rev = "719cd933", default-features = false }
revm-inspector = { package = "revm-inspector", git = "https://github.com/Galxe/revm", rev = "719cd933", default-features = false }
revm-context = { package = "revm-context", git = "https://github.com/Galxe/revm", rev = "719cd933", default-features = false }

ahash = "0.8"
rayon = "1.10.0"
atomic = "0.6.0"
parking_lot = "0.12"

# Alloy
alloy-evm = { package = "alloy-evm", git = "https://github.com/Galxe/alloy-evm", rev = "85e6450", default-features = false }

# async
futures = "0.3"
rand = "0.8.5"
auto_impl = "1"
lazy_static = "1.5.0"
dashmap = "6.0"

# metrics
metrics = "0.24"
metrics-derive = "0.1"

[dev-dependencies]
criterion = "0.5.1"
metrics-util = "0.19.0"
walkdir = "2.5.0"
rayon = "1.10.0"
tikv-jemallocator = "0.6"
bincode = "1.3.3"
serde_json = "1.0.94"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"

[[bench]]
name = "gigagas"
harness = false

[[bench]]
name = "mainnet"
harness = false

[[bench]]
name = "continuous_blocks"
harness = false

[profile.release]
codegen-units = 1
panic = "abort"
lto = "fat"

[profile.bench]
debug = 2
opt-level = 3
lto = "off"

[features]
update-test-submodule = ["update-submodule-test-data", "update-submodule-ethereum-tests"]
update-submodule-test-data = []
update-submodule-ethereum-tests = []
